### ISSUE TITLE
asam_vit_h checkpoint

### ISSUE THREAD

**Issue by russel0719** [luckybird1994/ASAM#1]
Thank you for your great work!

Is there any plan to release the model checkpoint/weight files of 'asam_vit_h.pth' trained with sam_vit_h?

or 'asam_hq_vit_h.pth' trained with sam_hq_vit_h?

**Comment by luckybird1994** [comment]
Thanks for comments. Due to some company constraints, the ViT-H model cannot be released for now. Once the communication is complete, we will try to release it. Thank you for your understanding.

**Comment by russel0719** [comment]
> Thanks for comments. Due to some company constraints, the ViT-H model cannot be released for now. Once the communication is complete, we will try to release it. Thank you for your understanding.

Oh, I see. Thank you for your reply!
