### ISSUE TITLE
About the usage of external data

### ISSUE THREAD

**Issue by ppalantir** [luckybird1994/ASAM#2]
Thank you for your awesome work! I would like to ask a question about how to understand the setting/claim no external data were used for boosting SAM, yet the pre-trained Stable Diffusion was pre-trained on external data?

**Comment by luckybird1994** [comment]
No external data means that when we fine-tune SAM, we only use a subset of SA-1B. As a further example, EfficientSAM uses additional ImageNet-1k data to train the encoder, which in our opinion means that additional data is used to retrain SAM.
