### ISSUE TITLE
How to convert the train.json file to a single image corresponding to a single .json file.

### ISSUE THREAD

**Issue by sajdhak** [luckybird1994/ASAM#3]
Hello, I now have a CoCo type dataset, how can I convert it to SA-1B format?
![image](https://github.com/luckybird1994/ASAM/assets/173120266/6dbe8e81-e8ab-4570-8141-0078a74ec69c)

![image](https://github.com/luckybird1994/ASAM/assets/173120266/1b831788-09a3-4657-a274-49661493f28b)

**Comment by hkxiao** [comment]
You can directly decode the coco-format mask and organize the folder structure as [this](https://huggingface.co/datasets/xhk/ASAM-Datasets/blob/main/SAM-1B.zip). It is worth mentioned that we don`t use the sa_x.json files in training process, so you can ignore them.

**Comment by sajdhak** [comment]
> You can directly decode the coco-format mask and organize the folder structure as [this](https://huggingface.co/datasets/xhk/ASAM-Datasets/blob/main/SAM-1B.zip). It is worth mentioned that we don`t use the sa_x.json files in training process, so you can ignore them.

Thank you very much, we will try it.
