### ISSUE TITLE
Inferior segmentation performance observed on fluorescent microscope images.

### ISSUE THREAD

**Issue by alphacygni33** [luckybird1994/ASAM#8]
Thanks for your great work and the demo, which is very helpful. I tried the demo with some sample images from my fluorescent microscope dataset (an example is attached below), and I found that the mask generated by ASAM is actually more noisy and less consistent than the original SAM:

Here's an example image:
![30357_29734_1024_1024](https://github.com/user-attachments/assets/298d1d99-5a43-4645-9e8f-ba26d4b2884b)

Here's the screenshot of the output masks:
![image](https://github.com/user-attachments/assets/4c1a1228-dd0a-4247-8a89-9a7c4c6b0c60)

I used the scribble_box task and set the top-left point and the bottom-right point of the region that I'd like to run segmentation on. I didn't change the default parameter settings. Based on the results of my fluorescent cell images, it seems that ASAM is actually less robust than the original SAM? I found this odd because ASAM is fine-tuned with adversarial examples and AT supposedly should at least improve the model's robustness against different types of noise? Granted the fluorescent images are semantically far from the natural light photography images in SA-1B, it's still strange to me why the original SAM would have a more consistent performance. What do you think might be the reason why ASAM produced inferior results on this particular type of images than SAM?

Looking forward to hearing your opinion on this subject.

**Comment by luckybird1994** [comment]
Thank you for your interest in our work. For these fluorescent images, which differ from the commonly used RGB images, we also find that changing the prompts would improves the results generated by ASAM compared to SAM, as shown in the figure below. Therefore, our understanding is that the robustness of either ASAM or SAM may need further enhancement, and this is a new direction worth exploring. 
![WechatIMG2176](https://github.com/user-attachments/assets/aff17378-f415-41c4-827d-04be77be1d2d)

**Comment by alphacygni33** [comment]
Thanks for your response! Closing this thread.
